# data related parameters
data_csv_path: "./data/test/ten-rows-template.csv"
# data_csv_path: "./data/test/lens-export.jsonl"

# skill extractor related parameters
sentence_model: "all-MiniLM-L6-v2"
device: "cuda" # or "cpu"
skill_threshold: 0.6
batch_size: 32
link2skill_mapping_file: '/home/nikifori/Desktop/thesis/repo/resources/ESCO_link2skill_mapping.csv' # if None it will try to find the file in "project/resources/ESCO_link2skill_mapping.csv"
